/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ListTreeRequest, ListTreeResult, ReadConfigRequest, ReadConfigResult, ReadFileRequest, ReadFileResult, ReadImageRequest, ReadImageResult, ReadThemeRequest, ReadThemeResult, WriteFileRequest, WriteFileResult } from '@undeadsheep/dsh-file-preview/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$66696c6550726576696577 {
    listTree: (request: ListTreeRequest) => Promise<RemoteResult<ListTreeResult>>
    readConfig: (request: ReadConfigRequest) => Promise<RemoteResult<ReadConfigResult>>
    readFile: (request: ReadFileRequest) => Promise<RemoteResult<ReadFileResult>>
    readImage: (request: ReadImageRequest) => Promise<RemoteResult<ReadImageResult>>
    readTheme: (request: ReadThemeRequest) => Promise<RemoteResult<ReadThemeResult>>
    writeFile: (request: WriteFileRequest) => Promise<RemoteResult<WriteFileResult>>
  }
  interface TypertRemoteMap {
    'filePreview/listTree': (request: ListTreeRequest) => Promise<RemoteResult<ListTreeResult>>
    'filePreview/readConfig': (request: ReadConfigRequest) => Promise<RemoteResult<ReadConfigResult>>
    'filePreview/readFile': (request: ReadFileRequest) => Promise<RemoteResult<ReadFileResult>>
    'filePreview/readImage': (request: ReadImageRequest) => Promise<RemoteResult<ReadImageResult>>
    'filePreview/readTheme': (request: ReadThemeRequest) => Promise<RemoteResult<ReadThemeResult>>
    'filePreview/writeFile': (request: WriteFileRequest) => Promise<RemoteResult<WriteFileResult>>
  }
  interface TypertRemoteNamespaceMap {
    'filePreview': TypertRemoteNamespace$66696c6550726576696577
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
