/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const FileTreeNodeRemoteCodec$schema = z.union([z.object({
  'type': z.literal("dir").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'children': z.array(z.lazy(() => FileTreeNodeRemoteCodec$schema)).readonly(),
}), z.object({
  'type': z.literal("file").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'size': z.number().readonly().optional(),
}), z.object({
  'type': z.literal("other").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'size': z.number().readonly().optional(),
})])
const _deepseek_ai_dsh_file_preview_filePreview_listTree_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_listTree_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.array(z.union([z.object({
  'type': z.literal("dir").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'children': z.array(z.lazy(() => FileTreeNodeRemoteCodec$schema)).readonly(),
}), z.object({
  'type': z.literal("file").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'size': z.number().readonly().optional(),
}), z.object({
  'type': z.literal("other").readonly(),
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'size': z.number().readonly().optional(),
})])).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("no-workspace").readonly(),
}), z.object({
  'code': z.literal("io-failure").readonly(),
  'message': z.string().readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_file_preview_filePreview_readConfig_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_readConfig_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'indentSize': z.number(),
  'useTabs': z.boolean(),
  'pollInterval': z.number(),
  'fontSize': z.number(),
}).readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_readFile_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_readFile_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string(),
  'content': z.string(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("io-failure").readonly(),
  'message': z.string().readonly(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'path': z.string().readonly(),
}), z.object({
  'code': z.literal("not-text").readonly(),
  'path': z.string().readonly(),
}), z.object({
  'code': z.literal("too-large").readonly(),
  'path': z.string().readonly(),
  'maxBytes': z.number().readonly(),
  'size': z.number().readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_file_preview_filePreview_readTheme_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_readTheme_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'colors': z.object({
  'keyword': z.string().optional(),
  'string': z.string().optional(),
  'number': z.string().optional(),
  'comment': z.string().optional(),
  'tag': z.string().optional(),
  'function': z.string().optional(),
  'type': z.string().optional(),
  'variable': z.string().optional(),
}).readonly(),
  'bg': z.union([z.literal(null), z.string()]).readonly(),
  'fg': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_writeFile_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'content': z.string().readonly(),
})
const _deepseek_ai_dsh_file_preview_filePreview_writeFile_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("io-failure").readonly(),
  'message': z.string().readonly(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'path': z.string().readonly(),
}), z.object({
  'code': z.literal("write-denied").readonly(),
  'path': z.string().readonly(),
})]).readonly(),
})])

export const TYPERT = {
  package: '@undeadsheep/dsh-file-preview',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@undeadsheep/dsh-file-preview#filePreview/listTree',
      service: 'filePreview',
      namespace: 'filePreview',
      method: 'listTree',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@undeadsheep/dsh-file-preview/types#ListTreeRequest',
            schema: _deepseek_ai_dsh_file_preview_filePreview_listTree_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@undeadsheep/dsh-file-preview/types#ListTreeResult',
        schema: _deepseek_ai_dsh_file_preview_filePreview_listTree_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/file-preview/src/index.ts","line":103,"column":9},
    },
    {
      id: '@undeadsheep/dsh-file-preview#filePreview/readConfig',
      service: 'filePreview',
      namespace: 'filePreview',
      method: 'readConfig',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadConfigRequest',
            schema: _deepseek_ai_dsh_file_preview_filePreview_readConfig_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadConfigResult',
        schema: _deepseek_ai_dsh_file_preview_filePreview_readConfig_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/file-preview/src/index.ts","line":185,"column":9},
    },
    {
      id: '@undeadsheep/dsh-file-preview#filePreview/readFile',
      service: 'filePreview',
      namespace: 'filePreview',
      method: 'readFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadFileRequest',
            schema: _deepseek_ai_dsh_file_preview_filePreview_readFile_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadFileResult',
        schema: _deepseek_ai_dsh_file_preview_filePreview_readFile_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/file-preview/src/index.ts","line":115,"column":9},
    },
    {
      id: '@undeadsheep/dsh-file-preview#filePreview/readTheme',
      service: 'filePreview',
      namespace: 'filePreview',
      method: 'readTheme',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadThemeRequest',
            schema: _deepseek_ai_dsh_file_preview_filePreview_readTheme_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@undeadsheep/dsh-file-preview/types#ReadThemeResult',
        schema: _deepseek_ai_dsh_file_preview_filePreview_readTheme_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/file-preview/src/index.ts","line":148,"column":9},
    },
    {
      id: '@undeadsheep/dsh-file-preview#filePreview/writeFile',
      service: 'filePreview',
      namespace: 'filePreview',
      method: 'writeFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@undeadsheep/dsh-file-preview/types#WriteFileRequest',
            schema: _deepseek_ai_dsh_file_preview_filePreview_writeFile_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@undeadsheep/dsh-file-preview/types#WriteFileResult',
        schema: _deepseek_ai_dsh_file_preview_filePreview_writeFile_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/file-preview/src/index.ts","line":136,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host-facing Remote for the floating file-preview window.",
        "summary": "Host-facing Remote for the floating file-preview window.",
        "tags": [],
        "jsDoc": "/** Host-facing Remote for the floating file-preview window. */",
        "key": "filePreview",
        "exportName": "FilePreviewService",
        "members": [
          {
            "kind": "method",
            "name": "listTree",
            "signature": "@Remote('listTree') async listTree(request: ListTreeRequest): Promise<ListTreeResult>"
          },
          {
            "kind": "method",
            "name": "readFile",
            "signature": "@Remote('readFile') async readFile(request: ReadFileRequest): Promise<ReadFileResult>"
          },
          {
            "kind": "method",
            "name": "writeFile",
            "signature": "@Remote('writeFile') async writeFile(request: WriteFileRequest): Promise<WriteFileResult>"
          },
          {
            "kind": "method",
            "name": "readTheme",
            "signature": "@Remote('readTheme') async readTheme(request: ReadThemeRequest): Promise<ReadThemeResult>"
          },
          {
            "kind": "method",
            "name": "readConfig",
            "signature": "@Remote('readConfig') async readConfig(request: ReadConfigRequest): Promise<ReadConfigResult>"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ConfigPayload",
            "declaration": "export interface ConfigPayload {\n    indentSize: number;\n    useTabs: boolean;\n    pollInterval: number;\n    fontSize: number;\n}"
          },
          {
            "name": "FilePreviewFailure",
            "declaration": "export type FilePreviewFailure = FilePreviewNoWorkspace | FilePreviewNotFound | FilePreviewNotText | FilePreviewTooLarge | FilePreviewWriteDenied | FilePreviewIoFailure;"
          },
          {
            "name": "FilePreviewIoFailure",
            "declaration": "export interface FilePreviewIoFailure {\n    readonly code: 'io-failure';\n    readonly message: string;\n}"
          },
          {
            "name": "FilePreviewNotFound",
            "declaration": "export interface FilePreviewNotFound {\n    readonly code: 'not-found';\n    readonly path: string;\n}"
          },
          {
            "name": "FilePreviewNotText",
            "declaration": "export interface FilePreviewNotText {\n    readonly code: 'not-text';\n    readonly path: string;\n}"
          },
          {
            "name": "FilePreviewNoWorkspace",
            "declaration": "export interface FilePreviewNoWorkspace {\n    readonly code: 'no-workspace';\n}"
          },
          {
            "name": "FilePreviewTooLarge",
            "declaration": "export interface FilePreviewTooLarge {\n    readonly code: 'too-large';\n    readonly path: string;\n    readonly maxBytes: number;\n    readonly size: number;\n}"
          },
          {
            "name": "FilePreviewWriteDenied",
            "declaration": "export interface FilePreviewWriteDenied {\n    readonly code: 'write-denied';\n    readonly path: string;\n}"
          },
          {
            "name": "FileTreeNode",
            "declaration": "export type FileTreeNode = { readonly type: 'dir'; readonly name: string; readonly path: string; readonly children: FileTreeNode[]; } | { readonly type: 'file'; readonly name: string; readonly path: string; readonly size?: number; } | { readonly type: 'other'; readonly name: string; readonly path: string; readonly size?: number; };"
          },
          {
            "name": "ListTreeRequest",
            "declaration": "export interface ListTreeRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ListTreeResult",
            "declaration": "export type ListTreeResult = Ok<FileTreeNode[]> | Rejected<FilePreviewNoWorkspace | FilePreviewIoFailure>;"
          },
          {
            "name": "Ok",
            "declaration": "export interface Ok<T> {\n    readonly ok: true;\n    readonly value: T;\n}"
          },
          {
            "name": "PreviewThemeColors",
            "declaration": "export interface PreviewThemeColors {\n    keyword?: string;\n    string?: string;\n    number?: string;\n    comment?: string;\n    tag?: string;\n    function?: string;\n    type?: string;\n    variable?: string;\n}"
          },
          {
            "name": "ReadConfigRequest",
            "declaration": "export interface ReadConfigRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ReadConfigResult",
            "declaration": "export type ReadConfigResult = Ok<ConfigPayload>;"
          },
          {
            "name": "ReadFileRequest",
            "declaration": "export interface ReadFileRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n}"
          },
          {
            "name": "ReadFileResult",
            "declaration": "export type ReadFileResult = Ok<{ path: string; content: string; }> | Rejected<FilePreviewNotFound | FilePreviewNotText | FilePreviewTooLarge | FilePreviewIoFailure>;"
          },
          {
            "name": "ReadThemeRequest",
            "declaration": "export interface ReadThemeRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ReadThemeResult",
            "declaration": "export type ReadThemeResult = Ok<ThemePayload>;"
          },
          {
            "name": "Rejected",
            "declaration": "export interface Rejected<E extends FilePreviewFailure> {\n    readonly ok: false;\n    readonly error: E;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "ThemePayload",
            "declaration": "export interface ThemePayload {\n    readonly colors: PreviewThemeColors;\n    readonly bg: string | null;\n    readonly fg: string | null;\n}"
          },
          {
            "name": "WriteFileRequest",
            "declaration": "export interface WriteFileRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n    readonly content: string;\n}"
          },
          {
            "name": "WriteFileResult",
            "declaration": "export type WriteFileResult = Ok<{ path: string; }> | Rejected<FilePreviewNotFound | FilePreviewWriteDenied | FilePreviewIoFailure>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
